"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import type { Alert } from "@/lib/types";

// --- Types matching server-side simulation events ---

export interface PositionUpdate {
  type: "position";
  shipmentId: string;
  lat: number;
  lng: number;
  speed: number;
  heading: number;
  timestamp: string;
  progressPercent: number;
  temperature: number | null;
  humidity: number | null;
}

export interface AlertEvent {
  type: "alert";
  alert: Alert;
}

interface HeartbeatEvent {
  type: "heartbeat";
  tick: number;
  running: boolean;
  speed: number;
  simulatedTime: number;
}

interface StateEvent {
  type: "state";
  running: boolean;
  speed: number;
  tick: number;
  simulatedTime: number;
}

type SSEEvent = PositionUpdate | AlertEvent | HeartbeatEvent | StateEvent;

export interface SimulationStatus {
  connected: boolean;
  running: boolean;
  speed: number;
  tick: number;
  simulatedTime: number;
}

export interface UseSimulationResult {
  /** Map of shipmentId → latest position update */
  positions: Map<string, PositionUpdate>;
  /** New alerts generated by the simulation */
  simulationAlerts: Alert[];
  /** Current simulation status */
  status: SimulationStatus;
  /** Control functions */
  start: () => Promise<void>;
  pause: () => Promise<void>;
  reset: () => Promise<void>;
  setSpeed: (speed: number) => Promise<void>;
}

async function sendControl(action: string, speed?: number): Promise<void> {
  try {
    await fetch("/api/simulation/control", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action, speed }),
    });
  } catch {
    // Ignore network errors in prototype
  }
}

export function useSimulation(): UseSimulationResult {
  const [positions, setPositions] = useState<Map<string, PositionUpdate>>(
    () => new Map()
  );
  const [simulationAlerts, setSimulationAlerts] = useState<Alert[]>([]);
  const [status, setStatus] = useState<SimulationStatus>({
    connected: false,
    running: false,
    speed: 1,
    tick: 0,
    simulatedTime: 0,
  });

  const eventSourceRef = useRef<EventSource | null>(null);
  const reconnectTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Connect to SSE stream
  useEffect(() => {
    function connect() {
      if (eventSourceRef.current) {
        eventSourceRef.current.close();
      }

      const es = new EventSource("/api/simulation/stream");
      eventSourceRef.current = es;

      es.onopen = () => {
        setStatus((prev) => ({ ...prev, connected: true }));
      };

      es.onmessage = (event) => {
        try {
          const data = JSON.parse(event.data) as SSEEvent;

          if (data.type === "position") {
            const pos = data as PositionUpdate;
            // Skip signal-lost markers (lat=0, lng=0)
            if (pos.lat === 0 && pos.lng === 0) {
              // Mark as signal lost — don't update position, let it fade
              return;
            }
            setPositions((prev) => {
              const next = new Map(prev);
              next.set(pos.shipmentId, pos);
              return next;
            });
          } else if (data.type === "alert") {
            const alertEvt = data as AlertEvent;
            setSimulationAlerts((prev) => {
              if (prev.some((a) => a.id === alertEvt.alert.id)) return prev;
              return [...prev, alertEvt.alert];
            });
          } else if (data.type === "heartbeat") {
            const hb = data as HeartbeatEvent;
            setStatus((prev) => ({
              ...prev,
              connected: true,
              running: hb.running,
              speed: hb.speed,
              tick: hb.tick,
              simulatedTime: hb.simulatedTime,
            }));
          } else if (data.type === "state") {
            const st = data as StateEvent;
            setStatus((prev) => ({
              ...prev,
              connected: true,
              running: st.running,
              speed: st.speed,
              tick: st.tick,
              simulatedTime: st.simulatedTime,
            }));
          }
        } catch {
          // Ignore parse errors
        }
      };

      es.onerror = () => {
        setStatus((prev) => ({ ...prev, connected: false }));
        es.close();
        // Reconnect after 3s
        reconnectTimerRef.current = setTimeout(connect, 3000);
      };
    }

    connect();

    return () => {
      if (eventSourceRef.current) {
        eventSourceRef.current.close();
      }
      if (reconnectTimerRef.current) {
        clearTimeout(reconnectTimerRef.current);
      }
    };
  }, []);

  const start = useCallback(async () => {
    await sendControl("start");
    setStatus((prev) => ({ ...prev, running: true }));
  }, []);

  const pause = useCallback(async () => {
    await sendControl("pause");
    setStatus((prev) => ({ ...prev, running: false }));
  }, []);

  const reset = useCallback(async () => {
    await sendControl("reset");
    setPositions(new Map());
    setSimulationAlerts([]);
    setStatus((prev) => ({ ...prev, running: false, tick: 0, simulatedTime: 0 }));
  }, []);

  const setSpeed = useCallback(async (speed: number) => {
    await sendControl("setSpeed", speed);
    setStatus((prev) => ({ ...prev, speed }));
  }, []);

  return { positions, simulationAlerts, status, start, pause, reset, setSpeed };
}
